apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms
  namespace: dev-ops-shams
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cms
  template:
    metadata:
      labels:
        app: cms
    spec:
      containers:
        - name: cms
          image: registry.gitlab.com/a10179/campaign-system/frontend/cms:0.1.6-beta
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: cms-configmap
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
              protocol: TCP
      imagePullSecrets:
        - name: gitlab-registry

---

apiVersion: v1
kind: Service
metadata:
  name: cms-service
  namespace: dev-ops-shams
spec:
  selector:
    app: cms
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1

kind: Ingress
metadata:
  name: cms-ingress
  namespace: dev-ops-shams
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-Forwarded-User,X-Forwarded-Email,X-Forwarded-Preferred-Username,X-Auth-Request-User, X-Auth-Request-Email"
  labels:
    name: cms-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: cms.dev-ops-shams.rdev.antwerptechnologies.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: cms-service
            port: 
              number: 3000
  tls:
    - hosts:
        - cms.dev-ops-shams.rdev.antwerptechnologies.com
      secretName: cms-tls

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: cms-configmap
  namespace: dev-ops-shams
data:
  VITE_APP_PREFIX: "BLUE.AI_CMS"
  VITE_APP_API_BASE_URL: "https://omni-core-api.rdev.antwerptechnologies.com"
