//#region Import
import type { IconType } from "@/ui"

import { lazy } from "react"
//#endregion

export enum IndustryIconEnum {
	"EMOJIONEMONOTONEARTISTPALETTE" = "EMOJIONEMONOTONEARTISTPALETTE",
	"FLUENTHANDSHAKE16FILLED" = "FLUENTHANDSHAKE16FILLED",
	"FLUENTPEOPLECOMMUNITY16FILLED" = "FLUENTPEOPLECOMMUNITY16FILLED",
	"FLUENTREALESTATE24FILLED" = "FLUENTREALESTATE24FILLED",
	"FLUENTWRENCHSETTINGS24REGULAR" = "FLUENTWRENCHSETTINGS24REGULAR",
	"ICBASELINEFOODBANK" = "ICBASELINEFOODBANK",
	"ICONOIRHEALTHCARE" = "ICONOIRHEALTHCARE",
	"ICONOIRTHREESTARSSOLID" = "ICONOIRTHREESTARSSOLID",
	"ICONPARKSOLIDBARBERBRUSH" = "ICONPARKSOLIDBARBERBRUSH",
	"ICONPARKSOLIDLOCAL" = "ICONPARKSOLIDLOCAL",
	"ICONPARKSOLIDUSERBUSINESS" = "ICONPARKSOLIDUSERBUSINESS",
	"ICROUNDSHOPIFY" = "ICROUNDSHOPIFY",
	"ICROUNDSHOPPINGCART" = "ICROUNDSHOPPINGCART",
	"MATERIALSYMBOLSBUSINESSCENTERROUNDED" = "MATERIALSYMBOLSBUSINESSCENTERROUNDED",
	"MATERIALSYMBOLSFASTFOODSHARP" = "MATERIALSYMBOLSFASTFOODSHARP",
	"MATERIALSYMBOLSLIGHTHEALTHANDBEAUTYSHARP" = "MATERIALSYMBOLSLIGHTHEALTHANDBEAUTYSHARP",
	"MATERIALSYMBOLSLIGHTREALESTATEAGENT" = "MATERIALSYMBOLSLIGHTREALESTATEAGENT",
	"MATERIALSYMBOLSLIGHTTRAVELLUGGAGEANDBAGS" = "MATERIALSYMBOLSLIGHTTRAVELLUGGAGEANDBAGS",
	"MATERIALSYMBOLSSELFCARE" = "MATERIALSYMBOLSSELFCARE",
	"MATERIALSYMBOLSSTARSROUNDED" = "MATERIALSYMBOLSSTARSROUNDED",
	"MDIACCOUNTSCHOOL" = "MDIACCOUNTSCHOOL",
	"RIPRESENTATIONLINE" = "RIPRESENTATIONLINE",
	"SOLARHANDSTARSBOLD" = "SOLARHANDSTARSBOLD",
	"SOLARSHOP2BOLD" = "SOLARSHOP2BOLD",
	"STREAMLINEHEALTHCARE2SOLID" = "STREAMLINEHEALTHCARE2SOLID",
	"STREAMLINEMEDICALCROSSSIGNHEALTHCARESOLID" = "STREAMLINEMEDICALCROSSSIGNHEALTHCARESOLID",
	"STREAMLINEQUALITYEDUCATIONSOLID" = "STREAMLINEQUALITYEDUCATIONSOLID",
	"STREAMLINETRAVELHOTELBELLSERVICECONCIERGEPORTERCALLRINGBELLHOPBELLRECEPTION" = "STREAMLINETRAVELHOTELBELLSERVICECONCIERGEPORTERCALLRINGBELLHOPBELLRECEPTION",
	"STREAMLINETRAVELHOTELSERVINGDOMEHANDPORTERSERVICEROOMPLATEHANDBELLHOPPLATTERGIVEFOOD" = "STREAMLINETRAVELHOTELSERVINGDOMEHANDPORTERSERVICEROOMPLATEHANDBELLHOPPLATTERGIVEFOOD",
	"ZONDICONSEDUCATION" = "ZONDICONSEDUCATION",
	"ZONDICONSLOCATIONFOOD" = "ZONDICONSLOCATIONFOOD",
}

const industriesIconsMap: Record<IndustryIconEnum, React.LazyExoticComponent<IconType>> = {
	EMOJIONEMONOTONEARTISTPALETTE: lazy(() => import("~icons/emojione-monotone/artist-palette")),
	FLUENTHANDSHAKE16FILLED: lazy(() => import("~icons/fluent/handshake-16-filled")),
	FLUENTPEOPLECOMMUNITY16FILLED: lazy(() => import("~icons/fluent/people-community-16-filled")),
	FLUENTREALESTATE24FILLED: lazy(() => import("~icons/fluent/real-estate-24-filled")),
	FLUENTWRENCHSETTINGS24REGULAR: lazy(() => import("~icons/fluent/wrench-settings-24-regular")),
	ICBASELINEFOODBANK: lazy(() => import("~icons/ic/baseline-food-bank")),
	ICONOIRHEALTHCARE: lazy(() => import("~icons/iconoir/healthcare")),
	ICONOIRTHREESTARSSOLID: lazy(() => import("~icons/iconoir/three-stars-solid")),
	ICONPARKSOLIDBARBERBRUSH: lazy(() => import("~icons/icon-park-solid/barber-brush")),
	ICONPARKSOLIDLOCAL: lazy(() => import("~icons/icon-park-solid/local")),
	ICONPARKSOLIDUSERBUSINESS: lazy(() => import("~icons/icon-park-solid/user-business")),
	ICROUNDSHOPIFY: lazy(() => import("~icons/ic/round-shopify")),
	ICROUNDSHOPPINGCART: lazy(() => import("~icons/ic/round-shopping-cart")),
	MATERIALSYMBOLSBUSINESSCENTERROUNDED: lazy(() => import("~icons/material-symbols/business-center-rounded")),
	MATERIALSYMBOLSFASTFOODSHARP: lazy(() => import("~icons/material-symbols/fastfood-sharp")),
	MATERIALSYMBOLSLIGHTHEALTHANDBEAUTYSHARP: lazy(() => import("~icons/material-symbols-light/health-and-beauty-sharp")),
	MATERIALSYMBOLSLIGHTREALESTATEAGENT: lazy(() => import("~icons/material-symbols-light/real-estate-agent")),
	MATERIALSYMBOLSLIGHTTRAVELLUGGAGEANDBAGS: lazy(() => import("~icons/material-symbols-light/travel-luggage-and-bags")),
	MATERIALSYMBOLSSELFCARE: lazy(() => import("~icons/material-symbols/self-care")),
	MATERIALSYMBOLSSTARSROUNDED: lazy(() => import("~icons/material-symbols/stars-rounded")),
	MDIACCOUNTSCHOOL: lazy(() => import("~icons/mdi/account-school")),
	RIPRESENTATIONLINE: lazy(() => import("~icons/ri/presentation-line")),
	SOLARHANDSTARSBOLD: lazy(() => import("~icons/solar/hand-stars-bold")),
	SOLARSHOP2BOLD: lazy(() => import("~icons/solar/shop-2-bold")),
	STREAMLINEHEALTHCARE2SOLID: lazy(() => import("~icons/streamline/health-care-2-solid")),
	STREAMLINEMEDICALCROSSSIGNHEALTHCARESOLID: lazy(
		() => import("~icons/streamline/medical-cross-sign-healthcare-solid")
	),
	STREAMLINEQUALITYEDUCATIONSOLID: lazy(() => import("~icons/streamline/quality-education-solid")),
	STREAMLINETRAVELHOTELBELLSERVICECONCIERGEPORTERCALLRINGBELLHOPBELLRECEPTION: lazy(
		() => import("~icons/streamline/travel-hotel-bell-service-concierge-porter-call-ring-bellhop-bell-reception")
	),
	STREAMLINETRAVELHOTELSERVINGDOMEHANDPORTERSERVICEROOMPLATEHANDBELLHOPPLATTERGIVEFOOD: lazy(
		() =>
			import(
				"~icons/streamline/travel-hotel-serving-dome-hand-porter-service-room-plate-hand-bellhop-platter-give-food"
			)
	),
	ZONDICONSEDUCATION: lazy(() => import("~icons/zondicons/education")),
	ZONDICONSLOCATIONFOOD: lazy(() => import("~icons/zondicons/location-food")),
}

export default industriesIconsMap
